# permissions for end users to edit pdfdocuments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pdfdocument-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pdfcotroller
    app.kubernetes.io/part-of: pdfcotroller
    app.kubernetes.io/managed-by: kustomize
  name: pdfdocument-editor-role
rules:
- apiGroups:
  - k8s.kannancustomresource.com.my.domain
  resources:
  - pdfdocuments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kannancustomresource.com.my.domain
  resources:
  - pdfdocuments/status
  verbs:
  - get
