apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    team: cert-study-group
    ghrepo: csgwebapp
    version: 0.0.1
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    team: cert-study-group
    ghrepo: csgwebapp
    version: 0.0.1
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      initContainers:
        - name: can-access-google
          image: nginx:1.25.3
          command: ['/bin/sh', '-c', 'echo Ready!']
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80
