apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-hostpath
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /etc/hostPath
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: slow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
        - name: main-container
          image: nginx:stable
          command: ["/bin/sh", "-c", "cat /data/data.txt; sleep infinity;"]
          volumeMounts:
            - name: pv-hostpath
              mountPath: /data
      initContainers:
        - name: init-container
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo 'init started...!!!' > /data/data.txt
          volumeMounts:
            - name: pv-hostpath
              mountPath: /data
      volumes:
        - name: pv-hostpath
          persistentVolumeClaim:
            claimName: pvc-hostpath

---


