apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-test
  namespace: resources-test
  labels:
    app: resources-test
spec:
  selector:
    matchLabels:
      app: resources-test
  replicas: 1
  template:
    metadata:
      labels:
        app: resources-test
    spec:
      containers:
        - name: busybox
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo 'running!'
                sleep 5
              done
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m

