apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    version: v1
spec:
  template:
    metadata:
      name: my-job
      labels:
        version: v1
    spec:
      containers:
        - name: print
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - |
              for i in $(seq 1 10); do
                echo "Hello Kubernetes! $i"
                sleep 1
              done
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 100
