apiVersion: v1
kind: Pod
metadata:
  name: resource-consumer-pod
spec:
  containers:
  - name: resource-consumer-container
    image: ubuntu:latest
    command:
    - "/bin/sh"
    - "-c"
    - "apt-get update && apt-get install -y stress && stress --cpu 1 --vm-bytes 128M --vm-keep"

