apiVersion: v1
kind: Pod
metadata:
  name: host-path-volume-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox:stable
    command: ["/bin/sh", "-c"]
    args: 
      - |
        cat /data/data.txt
    volumeMounts:
      - name: host-data
        mountPath: /data
  volumes:
    - name: host-data
      hostPath: 
        path: /etc/hostpath
        type: DirectoryOrCreate
      
