apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-test
  labels:
    app: liveness-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liveness-test
  template:
    metadata:
      labels:
        app: liveness-test
    spec:
      containers:
        - name: busybox
          image: busybox:stable
          command: ["/bin/sh", "-c",]
          args:
            - |
              while true; do
                echo 'running...!!!' 
                sleep 10;
              done  
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - echo 'healthcheck...!!!'    
            initialDelaySeconds: 5
            periodSeconds: 5
