apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  message: one more time changed message from configmap app-config
  application.properties: |
    key1=changed again value1
    ke2=changed again value2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-test
  labels:
    app: configmap-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-test
  template:
    metadata:
      labels:
        app: configmap-test
    spec:
      containers:
        - name: busybox
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo $(date)
                echo 'Message:' $MESSAGE
                cat /config/application.properties
                sleep 2
              done
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: message
          volumeMounts:
            - name: application-properties
              mountPath: /config
      volumes:
        - name: application-properties
          configMap:
            name: app-config
            items:
              - key: application.properties
                path: application.properties

