apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  sensitive.data: c2Vuc2l0aXZlIGRhdGEhCg==
  password.txt: dmVyeSBzZWNyZXQgY29udGVudAo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
  labels:
    app: secret-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
        - name: busybox
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          env:
            - name: SENSITIVE_STUFF
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: sensitive.data
          args:
            - |
              while true; do
                echo $(date)
                echo $SENSITIVE_STUFF;
                cat /config/passwords.txt
                sleep 5
              done
          volumeMounts:
            - name: secret-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: app-secret
            items:
              - key: password.txt
                path: passwords.txt



